[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
rand = "0.9.2"
vulkano = "0.34.0"
winit = "0.28.7"

[profile.dev]
opt-level = 1

[lints.rust]
unused_imports = "allow"
unused_variables = "allow"

[build]
rustflags = "-Aunused_imports"
